### ISSUE TITLE
Cannot destructure property `wpgraphql` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by Dave-Lindberg** [henrikwirth/gatsby-starter-wordpress-advanced#4]
Yarn Start produces the following error

``` 
ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPagesStatefully lifecycle:

Cannot read property 'uri' of null

   9 | 
  10 | exports.createPagesStatefully = async ({ graphql, actions, reporter }, options) => {
> 11 |   await createPages({ actions, graphql, reporter }, options)
     |   ^
  12 |   await createPosts({ actions, graphql, reporter }, options)
  13 | }
  14 | 

File: gatsby-node.js:11:3

  TypeError: Cannot read property 'uri' of null
  
  - createPages.js:107 
    /Users/dlindberg/Code/dl-gatsby-wpgql/create/createPages.js:107:30  
  - Array.map
  
  - createPages.js:106 
    /Users/dlindberg/Code/dl-gatsby-wpgql/create/createPages.js:106:24  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - createPages.js:104 async module.exports
    /Users/dlindberg/Code/dl-gatsby-wpgql/create/createPages.js:104:3
  
  - gatsby-node.js:11 async Object.exports.createPagesStatefully
    /Users/dlindberg/Code/dl-gatsby-wpgql/gatsby-node.js:11:3
  

failed createPagesStatefully - 0.484s
```
The GraphQL query from createPages.js

```
    query GET_PAGES($first:Int $after:String) {
        wpgraphql {
            pages(
                first: $first
                after: $after
                # This will make sure to only get the parent nodes and no children
                where: {
                    parent: null
                }
            ) {
                pageInfo {
                    hasNextPage
                    endCursor
                }
                nodes {                
                    id
                    title
                    pageId
                    content
                    uri
                    isFrontPage
                }
            }
        }
    }
```
yields the following errors in GraphiQL: 

```
{
  "errors": [
    {
      "message": "Internal server error",
      "path": [
        "wpgraphql",
        "pages",
        "nodes",
        0,
        "isFrontPage"
      ],
      "extensions": {
        "category": "internal"
      },
      "stack": [
        "GraphQLError: Internal server error",
        "    at Object.relocatedError (/Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/utils/index.cjs.js:3483:12)",
        "    at mergeDataAndErrors (/Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1404:34)",
        "    at /Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1432:66",
        "    at Array.forEach (<anonymous>)",
        "    at mergeDataAndErrors (/Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1430:27)",
        "    at /Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1432:66",
        "    at Array.forEach (<anonymous>)",
        "    at mergeDataAndErrors (/Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1430:27)",
        "    at checkResultAndHandleErrors (/Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1393:38)",
        "    at CheckResultAndHandleErrors.transformResult (/Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1389:16)",
        "    at /Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1576:40",
        "    at Array.reduceRight (<anonymous>)",
        "    at Transformer.transformResult (/Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1575:37)",
        "    at /Users/dlindberg/Code/dl-gatsby-wpgql/node_modules/@graphql-tools/delegate/index.cjs.js:1664:36",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "    at async Promise.all (index 0)"
      ]
    },
...
```

Appreciate your help as I work through this [very helpful tutorial](https://dev.to/nevernull/basic-wordpress-gatsby-setup-guide-to-gatsby-wordpress-starter-advanced-with-previews-i18n-and-more-44d8)

**Comment by Dave-Lindberg** [comment]
This error _only_ occurs when "isFrontPage" is selected (wpgraphql/pages/nodes/isFrontPage). Disabling this option yields expected data.

**Comment by Dave-Lindberg** [comment]
Looks like this is a Gatsby issue. Closing this.

**Comment by henrikwirth** [comment]
@Dave-Lindberg Glad it got figured out :) I think usually this happens if something is messed up in the query.
